/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.SwingMSystem;
import javax.swing.UIManager;

import javax.swing.UnsupportedLookAndFeelException;

import javax.swing.JFrame;
/**
 *
 * @author konod
 */
public class loginFrame extends javax.swing.JFrame {

    /**
     * Creates new form loginFrame
     */
    public loginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lvl1_LoginPanel = new javax.swing.JPanel();
        lvl2_UserIcon = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lvl2_ManamentTitle = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lvl2_InputText = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lvl3_UserTF = new com.raven.componet.IconTextField();
        lvl3_PasswordTF = new com.raven.componet.IconTextField();
        Lvl2_LoginButton = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        jTextField3.setForeground(new java.awt.Color(102, 153, 0));
        jTextField3.setText("jTextField2");
        jTextField3.setPreferredSize(new java.awt.Dimension(20, 22));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel5.setText("USER NAME ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(50, 50, 50))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        lvl1_LoginPanel.setPreferredSize(new java.awt.Dimension(400, 390));
        lvl1_LoginPanel.setLayout(new java.awt.GridLayout(4, 0));

        lvl2_UserIcon.setBackground(new java.awt.Color(238, 245, 245));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com.raven.Icon/user_icon.png"))); // NOI18N

        javax.swing.GroupLayout lvl2_UserIconLayout = new javax.swing.GroupLayout(lvl2_UserIcon);
        lvl2_UserIcon.setLayout(lvl2_UserIconLayout);
        lvl2_UserIconLayout.setHorizontalGroup(
            lvl2_UserIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lvl2_UserIconLayout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        lvl2_UserIconLayout.setVerticalGroup(
            lvl2_UserIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lvl2_UserIconLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lvl1_LoginPanel.add(lvl2_UserIcon);

        lvl2_ManamentTitle.setBackground(new java.awt.Color(238, 245, 245));
        lvl2_ManamentTitle.setPreferredSize(new java.awt.Dimension(78, 404));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("MANAGEMENT SYSTEM");

        javax.swing.GroupLayout lvl2_ManamentTitleLayout = new javax.swing.GroupLayout(lvl2_ManamentTitle);
        lvl2_ManamentTitle.setLayout(lvl2_ManamentTitleLayout);
        lvl2_ManamentTitleLayout.setHorizontalGroup(
            lvl2_ManamentTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lvl2_ManamentTitleLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        lvl2_ManamentTitleLayout.setVerticalGroup(
            lvl2_ManamentTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lvl2_ManamentTitleLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        lvl1_LoginPanel.add(lvl2_ManamentTitle);

        lvl2_InputText.setBackground(new java.awt.Color(238, 245, 245));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("USER NAME ");

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setText("PASSWORD");

        lvl3_UserTF.setAutoscrolls(false);
        lvl3_UserTF.setName("lvl3_UserTF"); // NOI18N
        lvl3_UserTF.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/com.raven.Icon/userText_icon.png"))); // NOI18N
        lvl3_UserTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lvl3_UserTFFocusLost(evt);
            }
        });
        lvl3_UserTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lvl3_UserTFActionPerformed(evt);
            }
        });

        lvl3_PasswordTF.setName("lvl3_PasswordTF"); // NOI18N
        lvl3_PasswordTF.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/com.raven.Icon/lock_icon.png"))); // NOI18N
        lvl3_PasswordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lvl3_PasswordTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lvl2_InputTextLayout = new javax.swing.GroupLayout(lvl2_InputText);
        lvl2_InputText.setLayout(lvl2_InputTextLayout);
        lvl2_InputTextLayout.setHorizontalGroup(
            lvl2_InputTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lvl2_InputTextLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lvl2_InputTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lvl2_InputTextLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(lvl3_UserTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(lvl2_InputTextLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(36, 36, 36)
                        .addComponent(lvl3_PasswordTF, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)))
                .addGap(104, 104, 104))
        );
        lvl2_InputTextLayout.setVerticalGroup(
            lvl2_InputTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lvl2_InputTextLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(lvl2_InputTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lvl3_UserTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lvl2_InputTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lvl3_PasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(75, 75, 75))
        );

        lvl1_LoginPanel.add(lvl2_InputText);

        Lvl2_LoginButton.setBackground(new java.awt.Color(238, 245, 245));

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Lvl2_LoginButtonLayout = new javax.swing.GroupLayout(Lvl2_LoginButton);
        Lvl2_LoginButton.setLayout(Lvl2_LoginButtonLayout);
        Lvl2_LoginButtonLayout.setHorizontalGroup(
            Lvl2_LoginButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Lvl2_LoginButtonLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        Lvl2_LoginButtonLayout.setVerticalGroup(
            Lvl2_LoginButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lvl2_LoginButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        lvl1_LoginPanel.add(Lvl2_LoginButton);

        getContentPane().add(lvl1_LoginPanel, java.awt.BorderLayout.WEST);
        lvl1_LoginPanel.getAccessibleContext().setAccessibleName("lvl1_LoginPanel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lvl3_PasswordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lvl3_PasswordTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lvl3_PasswordTFActionPerformed

    private void lvl3_UserTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lvl3_UserTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lvl3_UserTFActionPerformed

    private void lvl3_UserTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lvl3_UserTFFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_lvl3_UserTFFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
           
//      try {
//    UIManager.setLookAndFeel( new FlatLightLaf() );
//        } catch( UnsupportedLookAndFeelException ex ) {
//    System.err.println( "Failed to initialize LaF" );
//    }       

       java.awt.EventQueue.invokeLater(() -> {
    loginFrame frame = new loginFrame();
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.setLocationRelativeTo(null);
    frame.setVisible(true);
});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Lvl2_LoginButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel lvl1_LoginPanel;
    private javax.swing.JPanel lvl2_InputText;
    private javax.swing.JPanel lvl2_ManamentTitle;
    private javax.swing.JPanel lvl2_UserIcon;
    private com.raven.componet.IconTextField lvl3_PasswordTF;
    private com.raven.componet.IconTextField lvl3_UserTF;
    // End of variables declaration//GEN-END:variables
}
