/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ActionPanel;

import com.Dao.StudentDao;
import com.EventInterface.EventActionStudent;
import com.JdialogAction.InputDialog;
import com.JdialogAction.InputDialogStudent;
import com.JdialogAction.StudentDetail;
import com.model.ModelStudent;
import com.model.ModelUser;
import java.awt.Frame;
import javax.swing.SwingUtilities;

/**
 *
 * @author konod
 */
public class StudentPanel extends javax.swing.JPanel {
    private final StudentDao studentDao;
    private ModelUser loginUser ; 
    /**
     * Creates new form StudentPanel
     */
    public StudentPanel(ModelUser loginUser ) {
        studentDao = new StudentDao();
        this.loginUser = loginUser;
      
        initComponents();
         
        initTableData();
         if(loginUser.getUserRole() == 1)
         {   
             table1.setTableVisible(false);
             ActionLabel.setVisible(false);
             UserAddingButton.setVisible(false);
         }
            
    }
     private void Reload() {
        table1.ClearTable();
        initTableData();
    }

    private void initTableData() {
        EventActionStudent eventAction = new EventActionStudent() {
            @Override
            public void delete(ModelStudent student) {
                 if(table1.isEditing())
        {   
            table1.getCellEditor().stopCellEditing();
        }
       
     
        studentDao.deleteStudent(student.getID());
                Reload();
            }

            @Override
            public void update(ModelStudent student) {
                 if(table1.isEditing())
        {
            table1.getCellEditor().stopCellEditing();
        }
             InputDialogStudent inputDialog = new InputDialogStudent((Frame) SwingUtilities.getWindowAncestor(table1), true,student);

            inputDialog.setVisible(true);
                Reload();
            }

            @Override
            public void view(ModelStudent student) {
                if(table1.isEditing())
        {
            table1.getCellEditor().stopCellEditing();
        }
                StudentDetail inputDialog = new StudentDetail((Frame) SwingUtilities.getWindowAncestor(table1), true,student,loginUser);

            inputDialog.setVisible(true);
                Reload();
            }
        };

    String selectedMajor = MAJORCOMBOBOX.getSelectedItem().toString();
    String selectedQuality = QUALITYCOMBOBOX.getSelectedItem().toString();

    // Clear the existing rows in the table
    table1.ClearTable();
    int CountStudent =0 ; 
    // Loop through students and filter based on the selected values
    for (ModelStudent student : studentDao.getAllStudents()) {
        // Convert major and quality to lowercase for case-insensitive comparison
        String studentMajor = student.getMajor().toLowerCase();
        String studentQuality = student.getEducationQuality().toLowerCase();

        // Check if the student matches the selected values
        if (("ALL".equalsIgnoreCase(selectedMajor) || selectedMajor.equalsIgnoreCase(studentMajor)) &&
            ("All".equalsIgnoreCase(selectedQuality) || selectedQuality.equalsIgnoreCase(studentQuality))) {
            table1.addRow(student.toRowTable(eventAction));
            CountStudent++ ; 
        }
    }
    jLabel4.setText("Student Number : "+CountStudent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        MAJORCOMBOBOX = new javax.swing.JComboBox<>();
        QUALITYCOMBOBOX = new javax.swing.JComboBox<>();
        customTextField1 = new com.CustomComponent.CustomTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lightBule2 = new PaintComponent.LightBule();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        blueGradianPain1 = new PaintComponent.BlueGradianPain();
        ActionLabel = new javax.swing.JLabel();
        UserAddingButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new com.SwingTable.Table();

        jButton1.setText("jButton1");

        setPreferredSize(new java.awt.Dimension(1058, 741));
        setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.X_AXIS));

        MAJORCOMBOBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL", "FL", "ID", "AC", "SSH", "EE", "IT", "AS", "BA", "CE", "EHS LC", "FB", "MT", "SS", "LW", "DP" }));
        MAJORCOMBOBOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAJORCOMBOBOXActionPerformed(evt);
            }
        });
        jPanel3.add(MAJORCOMBOBOX);

        QUALITYCOMBOBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "RU", "JP", "HQ" }));
        QUALITYCOMBOBOX.setPreferredSize(new java.awt.Dimension(72, 50));
        QUALITYCOMBOBOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QUALITYCOMBOBOXActionPerformed(evt);
            }
        });
        jPanel3.add(QUALITYCOMBOBOX);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                    .addComponent(customTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(customTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 20));

        lightBule2.setPreferredSize(new java.awt.Dimension(330, 280));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Count :");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Student Number : 0");

        javax.swing.GroupLayout lightBule2Layout = new javax.swing.GroupLayout(lightBule2);
        lightBule2.setLayout(lightBule2Layout);
        lightBule2Layout.setHorizontalGroup(
            lightBule2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lightBule2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lightBule2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        lightBule2Layout.setVerticalGroup(
            lightBule2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lightBule2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jPanel4.add(lightBule2);

        blueGradianPain1.setPreferredSize(new java.awt.Dimension(330, 280));

        ActionLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ActionLabel.setForeground(new java.awt.Color(153, 255, 255));
        ActionLabel.setText("Student Action :");

        UserAddingButton.setBackground(new java.awt.Color(0, 153, 153));
        UserAddingButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        UserAddingButton.setForeground(new java.awt.Color(0, 102, 102));
        UserAddingButton.setText("Add Student");
        UserAddingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserAddingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout blueGradianPain1Layout = new javax.swing.GroupLayout(blueGradianPain1);
        blueGradianPain1.setLayout(blueGradianPain1Layout);
        blueGradianPain1Layout.setHorizontalGroup(
            blueGradianPain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blueGradianPain1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(blueGradianPain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ActionLabel)
                    .addComponent(UserAddingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        blueGradianPain1Layout.setVerticalGroup(
            blueGradianPain1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blueGradianPain1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ActionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserAddingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        jPanel4.add(blueGradianPain1);

        jPanel5.setLayout(new java.awt.BorderLayout());

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "START YEAR", "END YEAR", "MAJOR", "EQ", "PHONE", "ACTION"
            }
        ));
        jScrollPane2.setViewportView(table1);

        jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void customTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customTextField1KeyPressed
     
        
    }//GEN-LAST:event_customTextField1KeyPressed
    
    private void MAJORCOMBOBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAJORCOMBOBOXActionPerformed
    Reload() ;
// TODO add your handling code here:
    }//GEN-LAST:event_MAJORCOMBOBOXActionPerformed

    private void UserAddingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserAddingButtonActionPerformed
        if(table1.isEditing())
        {
            table1.getCellEditor().stopCellEditing();
        }
        InputDialogStudent inputDialog = new InputDialogStudent((Frame) SwingUtilities.getWindowAncestor(table1), true);

        inputDialog.setVisible(true);

        Reload();
        // Create a new JDialog
    }//GEN-LAST:event_UserAddingButtonActionPerformed

    private void QUALITYCOMBOBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QUALITYCOMBOBOXActionPerformed
    Reload() ;
// TODO add your handling code here:
    }//GEN-LAST:event_QUALITYCOMBOBOXActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActionLabel;
    private javax.swing.JComboBox<String> MAJORCOMBOBOX;
    private javax.swing.JComboBox<String> QUALITYCOMBOBOX;
    private javax.swing.JButton UserAddingButton;
    private PaintComponent.BlueGradianPain blueGradianPain1;
    private com.CustomComponent.CustomTextField customTextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private PaintComponent.LightBule lightBule2;
    private com.SwingTable.Table table1;
    // End of variables declaration//GEN-END:variables

    
}
