/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ActionPanel;

import com.Dao.UserDao;
import com.EventInterface.EventActionUser;
import com.JdialogAction.InputDialog;
import com.JdialogAction.LoginHistoryDialog;
import com.model.ModelUser;
import java.awt.Frame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author konod
 */
public class UserPanel extends javax.swing.JPanel {
   
  
     private final UserDao userDao; 
    private static InputDialog customDialog;
    private  ModelUser loginUser ;
    private static void openCustomFrame(JPanel parentFrame) {

        customDialog.setLocationRelativeTo(parentFrame);
        customDialog.setVisible(true);

        // Set focus to the text field when the custom dialog is opened
    }

    
    private void Reload()
    {   
        usertable.ClearTable();
        
        init() ; 
        initTableData() ; 
        
        
    }
     private void init() {
        // button to add the user 
       
    }

    // the Event that will be pass into the actionButton 
   private void initTableData() {
       
     EventActionUser eventAction = new EventActionUser() {
        @Override
        public void delete(ModelUser user) {
        if(usertable.isEditing())
        {   
            usertable.getCellEditor().stopCellEditing();
        }
       
     
        userDao.deleteUser(user.getUserID());
        Reload();
        }

        @Override
        public void update(ModelUser user) {
            if(usertable.isEditing())
        {
            usertable.getCellEditor().stopCellEditing();
        }
             InputDialog inputDialog = new InputDialog((Frame) SwingUtilities.getWindowAncestor(usertable), true,user);

            inputDialog.setVisible(true);
          
            Reload();
         
        }

        @Override
        public void view(ModelUser user) {
            LoginHistoryDialog logindialog =  new LoginHistoryDialog((Frame) SwingUtilities.getWindowAncestor(usertable), true,user) ;
            logindialog.setVisible(true); 
            
            Reload();
            
        }
    };
     
    int CountUser =0 ; 
  // Get the selected values from the combo boxes
    String selectedStatus = UserStatusCombobox.getSelectedItem().toString();
    String selectedRole = UserRoleCombobox.getSelectedItem().toString();
    // Loop through users and filter based on the selected values
    for (ModelUser user : userDao.getAllEmployeeAndManager()) {
        // Convert status and role to strings
        String userStatus = (user.getStatus() == 0) ? "Normal" : "Blocked";
        String userRole = (user.getUserRole() == 0) ? "Manager" : (user.getUserRole() == 1) ? "Employee" : "Unknown";   
        // Check if the user matches the selected values
        if (("none".equalsIgnoreCase(selectedStatus) || selectedStatus.equalsIgnoreCase(userStatus)) &&
    ("All".equalsIgnoreCase(selectedRole) || selectedRole.equalsIgnoreCase(userRole))) {
    usertable.addRow(user.toRowTable(eventAction));
    CountUser++ ; 
}
    }
    jLabel4.setText("User Number : "+CountUser);

   
}
    public UserPanel(ModelUser loginUser ) {
        this.loginUser = loginUser ;
       
       // set the user of the sotfware false if not admin  
        userDao = new UserDao();
        initComponents();
        initTableData() ;
        if(loginUser.getUserRole() == 1 || loginUser.getUserRole()==0)
        { usertable.setTableVisible(false);
            jLabel2.setVisible(false);
            UserAddingButton.setVisible(false);
        }
    }
     



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        customTextField1 = new com.CustomComponent.CustomTextField();
        jPanel3 = new javax.swing.JPanel();
        UserStatusCombobox = new javax.swing.JComboBox<>();
        UserRoleCombobox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lightBule2 = new PaintComponent.LightBule();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        organGradientPaint2 = new PaintComponent.OrganGradientPaint();
        jLabel2 = new javax.swing.JLabel();
        UserAddingButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        usertable = new com.SwingTable.Table();

        jButton1.setText("jButton1");

        setPreferredSize(new java.awt.Dimension(1058, 741));
        setLayout(new java.awt.BorderLayout());

        customTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                customTextField1KeyPressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.X_AXIS));

        UserStatusCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "blocked", "normal" }));
        UserStatusCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserStatusComboboxActionPerformed(evt);
            }
        });
        jPanel3.add(UserStatusCombobox);

        UserRoleCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Employee", "Manager" }));
        UserRoleCombobox.setPreferredSize(new java.awt.Dimension(72, 50));
        UserRoleCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserRoleComboboxActionPerformed(evt);
            }
        });
        jPanel3.add(UserRoleCombobox);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(customTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(173, 173, 173)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(210, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(53, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 20));

        lightBule2.setPreferredSize(new java.awt.Dimension(330, 280));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("User Count :");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("User Number : 0");

        javax.swing.GroupLayout lightBule2Layout = new javax.swing.GroupLayout(lightBule2);
        lightBule2.setLayout(lightBule2Layout);
        lightBule2Layout.setHorizontalGroup(
            lightBule2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lightBule2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lightBule2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lightBule2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        lightBule2Layout.setVerticalGroup(
            lightBule2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lightBule2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jPanel4.add(lightBule2);

        organGradientPaint2.setMinimumSize(new java.awt.Dimension(330, 280));
        organGradientPaint2.setPreferredSize(new java.awt.Dimension(330, 280));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("User Action :");

        UserAddingButton.setBackground(new java.awt.Color(0, 153, 153));
        UserAddingButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        UserAddingButton.setForeground(new java.awt.Color(0, 102, 102));
        UserAddingButton.setText("Add User");
        UserAddingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserAddingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout organGradientPaint2Layout = new javax.swing.GroupLayout(organGradientPaint2);
        organGradientPaint2.setLayout(organGradientPaint2Layout);
        organGradientPaint2Layout.setHorizontalGroup(
            organGradientPaint2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(organGradientPaint2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(organGradientPaint2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(UserAddingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        organGradientPaint2Layout.setVerticalGroup(
            organGradientPaint2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(organGradientPaint2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserAddingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        jPanel4.add(organGradientPaint2);

        jPanel5.setLayout(new java.awt.BorderLayout());

        usertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ICON", "NAME", "BIRTH DAY", "PHONE ", "STATUS	", "ROLE	", "ACTION "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(usertable);

        jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void customTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customTextField1KeyPressed
     
        
    }//GEN-LAST:event_customTextField1KeyPressed
    
    private void UserAddingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserAddingButtonActionPerformed
       if(usertable.isEditing())
        {
            usertable.getCellEditor().stopCellEditing();
        }
            InputDialog inputDialog = new InputDialog((Frame) SwingUtilities.getWindowAncestor(usertable), true);

            inputDialog.setVisible(true);
          
            Reload();   
  // Create a new JDialog
     
                 
    }//GEN-LAST:event_UserAddingButtonActionPerformed

    private void UserStatusComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserStatusComboboxActionPerformed
         Reload();
    }//GEN-LAST:event_UserStatusComboboxActionPerformed

    private void UserRoleComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserRoleComboboxActionPerformed
        Reload();
    }//GEN-LAST:event_UserRoleComboboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UserAddingButton;
    private javax.swing.JComboBox<String> UserRoleCombobox;
    private javax.swing.JComboBox<String> UserStatusCombobox;
    private com.CustomComponent.CustomTextField customTextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private PaintComponent.LightBule lightBule2;
    private PaintComponent.OrganGradientPaint organGradientPaint2;
    private com.SwingTable.Table usertable;
    // End of variables declaration//GEN-END:variables

    
}
