/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.JdialogAction;

import com.model.ModelCertificate;
import java.awt.FlowLayout;
import java.text.SimpleDateFormat;
import javax.swing.JDialog;
import javax.swing.SwingConstants;

/**
 *
 * @author konod
 */
public class CertificateView extends javax.swing.JDialog {

    /**
     * Creates new form CertificateView
     */
    public CertificateView( JDialog  parent, boolean modal ,ModelCertificate certificate ) {
        super(parent, modal);
        initComponents();
        CERTIFICATE_NAME.setText(certificate.getCertificateName());
       

       SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd"); // Adjust the pattern as needed

        String formattedIssueDate = dateFormat.format(certificate.getIssueDate());
        String formattedExpiryDate = dateFormat.format(certificate.getExpiryDate());
        ISSUE_DATE.setText(formattedIssueDate);
        EXPIRE_DATE.setText(formattedExpiryDate);
        Student_ID.setText(certificate.getStudentID());
        Student_grade.setText("" + certificate.getGrade());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageAvatar1 = new com.CustomizeUIComponent.ImageAvatar();
        Student_grade = new java.awt.Label();
        ISSUE_DATE = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        EXPIRE_DATE = new java.awt.Label();
        containerPanel = new javax.swing.JPanel();
        CERTIFICATE_NAME = new java.awt.Label();
        label3 = new java.awt.Label();
        label2 = new java.awt.Label();
        label9 = new java.awt.Label();
        Student_ID = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(452, 618));
        setResizable(false);
        getContentPane().setLayout(null);

        imageAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ResourceImage/TonDucThang_certificate.jpg"))); // NOI18N
        getContentPane().add(imageAvatar1);
        imageAvatar1.setBounds(230, 250, 138, 131);

        Student_grade.setBackground(new java.awt.Color(255, 255, 255));
        Student_grade.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        Student_grade.setText("grade");
        getContentPane().add(Student_grade);
        Student_grade.setBounds(90, 320, 45, 25);

        ISSUE_DATE.setBackground(new java.awt.Color(255, 255, 255));
        ISSUE_DATE.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        ISSUE_DATE.setText("issue date");
        getContentPane().add(ISSUE_DATE);
        ISSUE_DATE.setBounds(80, 440, 101, 25);

        label6.setBackground(new java.awt.Color(255, 255, 255));
        label6.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        label6.setText("expire date");
        getContentPane().add(label6);
        label6.setBounds(270, 410, 82, 25);

        label7.setBackground(new java.awt.Color(255, 255, 255));
        label7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label7.setText("Student ID");
        getContentPane().add(label7);
        label7.setBounds(80, 230, 88, 28);

        label8.setBackground(new java.awt.Color(255, 255, 255));
        label8.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        label8.setText("issue date");
        getContentPane().add(label8);
        label8.setBounds(80, 410, 101, 25);

        EXPIRE_DATE.setBackground(new java.awt.Color(255, 255, 255));
        EXPIRE_DATE.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        EXPIRE_DATE.setText("issue date");
        getContentPane().add(EXPIRE_DATE);
        EXPIRE_DATE.setBounds(270, 440, 101, 25);

        containerPanel.setBackground(new java.awt.Color(255, 255, 255, 100));

        CERTIFICATE_NAME.setFont(new java.awt.Font("HelveticaNeueLT Std", 1, 18)); // NOI18N
        CERTIFICATE_NAME.setForeground(new java.awt.Color(153, 204, 255));
        CERTIFICATE_NAME.setText("PYTHON PROGRAM ");
        containerPanel.add(CERTIFICATE_NAME);
        CERTIFICATE_NAME.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(containerPanel);
        containerPanel.setBounds(80, 130, 290, 40);

        label3.setBackground(new java.awt.Color(255, 255, 255));
        label3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label3.setText("Certificate");
        getContentPane().add(label3);
        label3.setBounds(180, 170, 85, 28);

        label2.setBackground(new java.awt.Color(255, 255, 255, 100));
        label2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        label2.setText(" TON DUC THANG UNIVERSITY ");
        getContentPane().add(label2);
        label2.setBounds(90, 100, 278, 29);

        label9.setBackground(new java.awt.Color(255, 255, 255));
        label9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label9.setText("Grade");
        getContentPane().add(label9);
        label9.setBounds(80, 290, 54, 28);

        Student_ID.setBackground(new java.awt.Color(255, 255, 255));
        Student_ID.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        Student_ID.setText("Student mssv ");
        getContentPane().add(Student_ID);
        Student_ID.setBounds(90, 260, 101, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ResourceImage/certificate.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-6, 5, 460, 610);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(73, 113, 0, 0);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CertificateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CertificateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CertificateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CertificateView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label CERTIFICATE_NAME;
    private java.awt.Label EXPIRE_DATE;
    private java.awt.Label ISSUE_DATE;
    private java.awt.Label Student_ID;
    private java.awt.Label Student_grade;
    private javax.swing.JPanel containerPanel;
    private com.CustomizeUIComponent.ImageAvatar imageAvatar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    // End of variables declaration//GEN-END:variables
}
