/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.JdialogAction;

import com.Dao.CertificateDao;
import com.EventInterface.EventActionCertificate;
import com.EventInterface.EventActionStudent;
import com.model.ModelCertificate;
import com.model.ModelLoginHistory;
import com.model.ModelStudent;
import com.model.ModelUser;
import java.awt.Frame;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;

/**
 *
 * @author konod
 */
public class StudentDetail extends javax.swing.JDialog {

    /**
     * Creates new form StudentDetail
     */
    
    
    
    private ModelStudent student = null ; 
    private String relativePath ; 
    private CertificateDao certificateDao  ; 
    
     public StudentDetail(java.awt.Frame parent, boolean modal) {
    super(parent, modal) ; 
   
    initComponents();
//     init();
    setModalityType(ModalityType.APPLICATION_MODAL);
    }
     
    public StudentDetail(java.awt.Frame parent, boolean modal, ModelStudent student,ModelUser user) {
   
    super(parent, modal) ; 
     certificateDao =  new CertificateDao() ; 
    this.student = student ; 
    setModalityType(ModalityType.APPLICATION_MODAL);
    
    initComponents();
    init();
    initTableData() ;  
    if(user.getUserRole() == 1)
    { table1.setTableVisible(false);
       AddCertificate.setVisible(false);
    }
       
    }
    private void init() {
        
       StudentIdLabel.setText("ID : "+ student.getID());
       StudentNameLabel.setText("Name: "+ student.getName());
       BeginningYearVarible.setText("Beginning Year : "+ student.getBeginningYear());
       EndYearLabel.setText("End Year  : "+ student.getEndYear());
       MajorLabel.setText("Major  : "+ student.getMajor());

       EQLabel.setText("Education Quality : "+ student.getEducationQuality());
       PhoneLabel.setText("Phone : "+ student.getPhone());

        
        
    }
    private void initTableData() {
        EventActionCertificate eventAction = new EventActionCertificate() {
            @Override
            public void delete(ModelCertificate cef) {
                 if(table1.isEditing())
        {   
            table1.getCellEditor().stopCellEditing();
        }
       
     
        certificateDao.deleteCertificate(cef.getCertificateID());
                Reload();
            }

            @Override
            public void update(ModelCertificate cef) {
                InputDialogCertificate inputDialog = new InputDialogCertificate(StudentDetail.this,true, cef);

                inputDialog.setVisible(true);
                Reload();
            }

            @Override
            public void view(ModelCertificate student) {
       
            }
        };

        for (ModelCertificate cef : certificateDao.getCertificatesByStudentID(student.getID())) {
            
            table1.addRow(cef.toRowTable(eventAction));
        }
    }
      private void Reload() {
        table1.ClearTable();
        initTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        UserNameLabel = new javax.swing.JLabel();
        StudentNameLabel = new javax.swing.JLabel();
        StudentIdLabel = new javax.swing.JLabel();
        EndYearLabel = new javax.swing.JLabel();
        BeginningYearVarible = new javax.swing.JLabel();
        MajorLabel = new javax.swing.JLabel();
        PhoneLabel = new javax.swing.JLabel();
        EQLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        AddCertificate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new com.swing.table.Table();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1008, 526));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setPreferredSize(new java.awt.Dimension(300, 518));

        UserNameLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        UserNameLabel.setForeground(new java.awt.Color(0, 204, 204));
        UserNameLabel.setText("Student Detail");

        StudentNameLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        StudentNameLabel.setForeground(new java.awt.Color(0, 204, 204));
        StudentNameLabel.setText("Name : null");

        StudentIdLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        StudentIdLabel.setForeground(new java.awt.Color(0, 204, 204));
        StudentIdLabel.setText("ID: NULL");

        EndYearLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        EndYearLabel.setForeground(new java.awt.Color(0, 204, 204));
        EndYearLabel.setText("End Year : null");

        BeginningYearVarible.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BeginningYearVarible.setForeground(new java.awt.Color(0, 204, 204));
        BeginningYearVarible.setText("Beginning Year : null");

        MajorLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        MajorLabel.setForeground(new java.awt.Color(0, 204, 204));
        MajorLabel.setText("Major : null");

        PhoneLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        PhoneLabel.setForeground(new java.awt.Color(0, 204, 204));
        PhoneLabel.setText("Phone : null");

        EQLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        EQLabel.setForeground(new java.awt.Color(0, 204, 204));
        EQLabel.setText("Education Quality : null");

        AddCertificate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AddCertificate.setForeground(new java.awt.Color(0, 102, 102));
        AddCertificate.setText("Add Certificate");
        AddCertificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCertificateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(AddCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(AddCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BeginningYearVarible)
                            .addComponent(EndYearLabel)
                            .addComponent(StudentIdLabel)
                            .addComponent(StudentNameLabel)
                            .addComponent(MajorLabel)
                            .addComponent(PhoneLabel)
                            .addComponent(EQLabel)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(UserNameLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserNameLabel)
                .addGap(26, 26, 26)
                .addComponent(StudentIdLabel)
                .addGap(18, 18, 18)
                .addComponent(StudentNameLabel)
                .addGap(18, 18, 18)
                .addComponent(BeginningYearVarible)
                .addGap(18, 18, 18)
                .addComponent(EndYearLabel)
                .addGap(18, 18, 18)
                .addComponent(MajorLabel)
                .addGap(18, 18, 18)
                .addComponent(EQLabel)
                .addGap(18, 18, 18)
                .addComponent(PhoneLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2);

        jPanel1.setLayout(new java.awt.BorderLayout());

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENT ID ", " NAME", "ISSUE DATE", "EXPIRY DATE", "GRADE", "ACTION"
            }
        ));
        jScrollPane1.setViewportView(table1);
        if (table1.getColumnModel().getColumnCount() > 0) {
            table1.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddCertificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCertificateActionPerformed
          InputDialogCertificate inputDialog = new InputDialogCertificate(StudentDetail.this,true, this.student.getID());
           inputDialog.setVisible(true);
                Reload();
    }//GEN-LAST:event_AddCertificateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StudentDetail dialog = new StudentDetail(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCertificate;
    private javax.swing.JLabel BeginningYearVarible;
    private javax.swing.JLabel EQLabel;
    private javax.swing.JLabel EndYearLabel;
    private javax.swing.JLabel MajorLabel;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JLabel StudentIdLabel;
    private javax.swing.JLabel StudentNameLabel;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.swing.table.Table table1;
    // End of variables declaration//GEN-END:variables
}
